{% set name = "hatch-fancy-pypi-readme" %}
{% set version = "22.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_fancy_pypi_readme-{{ version }}.tar.gz
  sha256: 17e22bc66422de67643eba1815c4d77b3f487c354dd6ecef1763a8889efe7092

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hatch-fancy-pypi-readme=hatch_fancy_pypi_readme.__main__:main

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - hatchling
    - python >=3.7
    - tomli
    - typing-extensions

test:
  imports:
    - hatch_fancy_pypi_readme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hynek/hatch-fancy-pypi-readme
  summary: Fancy PyPI READMEs with Hatch
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
