{% set name = "hatch-fancy-pypi-readme" %}
{% set version = "22.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch_fancy_pypi_readme-{{ version }}.tar.gz
  sha256: 805065d11bcbb06a44e973bcbd7b1e842d93f3fae87ce1ba38ce3c8cd7cfa2fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hatch-fancy-pypi-readme=hatch_fancy_pypi_readme.__main__:main

requirements:
  host:
    - hatchling
    - hatch-fancy-pypi-readme >=22.4.0
    - pip
    - python >=3.7
  run:
    - hatchling
    - python >=3.7
    - tomli
    - typing-extensions

test:
  source_files:
    - tests
  imports:
    - hatch_fancy_pypi_readme
  commands:
    - pip check
    - hatch_fancy_pypi_readme --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/hynek/hatch-fancy-pypi-readme
  summary: Fancy PyPI READMEs with Hatch
  license: MIT
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
